/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2015-06-22 07:52:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.service.dmc.util.CssFileFilter;
import java.io.File;
import java.io.FileFilter;
import java.util.List;
import com.service.dmc.sql.QueryBean;
import com.service.dmc.util.CssFileFilter;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 	
	QueryBean bean = (QueryBean) request.getAttribute("bean"); 
	if(bean == null) {bean = new QueryBean();}

      out.write("\n");
      out.write("   \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"");
      out.print( application.getContextPath() );
      out.write("/javascript/jquery.js\"></script>\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"");
      out.print( application.getContextPath() );
      out.write("/javascript/jquery-ui.js\"></script>\n");
      out.write("<link id=\"theme\" rel=\"stylesheet\" href=\"");
      out.print( application.getContextPath() );
      out.write("/css/default.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var presets = [ \n");
      out.write("[\"\",\"\",\"\",\"\",\"\"], \n");
      out.write("[\"postgres-localhost\",\"org.postgresql.Driver\",\"jdbc:postgresql://localhost:5432/world\",\"dmc\",\"dmc001\"], \n");
      out.write("[\"postgres-heroku\",\"org.postgresql.Driver\",\"jdbc:postgres://ec2-54-83-205-164.compute-1.amazonaws.com:5432/d9v6d5uqacptit\",\"kyuljdoqfyziks\",\"x9LvzxTGy8izs-7NFY30VDhqT0\"], \n");
      out.write("[\"postgres-heroku-world\",\"org.postgresql.Driver\",\"jdbc:postgres://ec2-54-83-205-164.compute-1.amazonaws.com:5432/world\",\"kyuljdoqfyziks\",\"x9LvzxTGy8izs-7NFY30VDhqT0\"], \n");
      out.write("[\"mysql-heroku\",\"com.mysql.jdbc.Driver\",\"jdbc:mysql://us-cdbr-iron-east-02.cleardb.net:3306/heroku_126abff0eac31c8\",\"bf05d3bb2265c3\",\"fc67f770\"],\n");
      out.write("[\"mysql-localhost-world\",\"com.mysql.jdbc.Driver\",\"jdbc:mysql://localhost/world\",\"root\",\"root001\"],\n");
      out.write("[\"mysql-localhost-information_schema\",\"com.mysql.jdbc.Driver\",\"jdbc:mysql://localhost/information_schema\",\"root\",\"root001\"],\n");
      out.write("[\"postgres-template\",\"org.postgresql.Driver\",\"jdbc:postgresql://localhost/db\",\"user\",\"password\"], \n");
      out.write("[\"mysql-template\",\"com.mysql.jdbc.Driver\",\"jdbc:mysql://localhost/mysql\",\"user\",\"password\"],\n");
      out.write("[\"oracle-template\",\"oracle.jdbc.driver.OracleDriver\",\"jdbc:oracle:thin:@host:port:db\",\"user\",\"password\"]\n");
      out.write(" ]; \n");
      out.write("\n");
      out.write("var csspresets =  \n");
      out.write("[\"defalut.css\",\n");
      out.write(" \"black.css\",\n");
      out.write(" \"orange.css\",\n");
      out.write(" \"dark.css\"]; \n");
      out.write("\n");
      out.write("\n");
      out.write("jQuery(function ($) {\n");
      out.write("\n");
      out.write("\tfor (var i = 0; i < presets.length; i++) {\n");
      out.write("\t\t$(\"#preset\").append($('<option>').html(presets[i][0]).val(i));\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfor (var i = 0; i < csspresets.length; i++) {\n");
      out.write("\t\tvar $option = $('<option>').html(csspresets[i]).val(csspresets[i]).attr('id',csspresets[i]);\n");
      out.write("\t\t$(\"#css-list\").append($('<option>').html(csspresets[i]).val(csspresets[i]));\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t$(\"#default.css\").prop(\"selected\",true);\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t$(\"#query-buttons\").hide();\n");
      out.write("\n");
      out.write("\t$('#login').click(function() {\n");
      out.write("\n");
      out.write("    \t$(\"input[type='button']\").prop(\"disabled\",true);\n");
      out.write("\t\n");
      out.write("    \t$.ajax({\n");
      out.write("    \t\t  url: \"");
      out.print(application.getContextPath());
      out.write("/action\",\n");
      out.write("    \t\t  type: \"post\",\n");
      out.write("    \t\t  data: {event: \"login\",driver: $('#driver').val(),url: $('#url').val(),user: $('#user').val(),password: $('#password').val()}\n");
      out.write("    \t\t  }).done(function(data) {\n");
      out.write("            \t$('#query-box').html(data);\t\n");
      out.write("    \t\t\tif ($(data).filter('#error').size()){\n");
      out.write("    \t\t\t\t$('#query-box').html(data);\t\n");
      out.write("              \t} else {\n");
      out.write("                    $(\"#login-parameter\").hide();\n");
      out.write("                  \t$(\"#query-buttons\").show();\n");
      out.write("              \t} \n");
      out.write("              }).always(function() {\n");
      out.write("  \t\t    \t$(\"input[type='button']\").prop(\"disabled\",false);\n");
      out.write("\t  \t\t  });\n");
      out.write("    \t\n");
      out.write("       });\n");
      out.write("\n");
      out.write("    $('#execute').click(function() {\n");
      out.write("\n");
      out.write("    \t$(\"input[type='button']\").prop(\"disabled\",true);\n");
      out.write("\n");
      out.write("    \t$.ajax({\n");
      out.write("    \t\t  url: \"");
      out.print( application.getContextPath() );
      out.write("/action\",\n");
      out.write("    \t\t  type: \"post\",\n");
      out.write("    \t\t  data: {event: \"execute\",driver: $('#driver').val(),url: $('#url').val(),user: $('#user').val(),password: $('#password').val(),query: $('#sql').val(),}\n");
      out.write("\t\t  }).done(function(data) {\n");
      out.write("\t\t\t\t$('#result').html(data);\n");
      out.write("    \t\t\n");
      out.write("\t\t  }).always(function() {\n");
      out.write("\t\t    \t$(\"input[type='button']\").prop(\"disabled\",false);\n");
      out.write("\t  \t});\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\t$('#history').click(function() {\n");
      out.write("    \t$.ajax({\n");
      out.write("  \t\t  url: \"");
      out.print( application.getContextPath() );
      out.write("/action\",\n");
      out.write("  \t\t  type: \"post\",\n");
      out.write("  \t\t  data: {event: \"history\",driver: $('#driver').val(),url: $('#url').val(),user: $('#user').val(),password: $('#password').val(),query: $('#sql').val(),}\n");
      out.write("  \t\t}).done(function(data) {\n");
      out.write("  \t\t\t$('#dialog').html(data);\n");
      out.write("  \t\t\tif($('#dialog').dialog(\"instance\")){\n");
      out.write("  \t\t\t\t$('#dialog').dialog();\n");
      out.write("  \t\t\t}else {\n");
      out.write("  \t  \t\t\t$('#dialog').dialog({width: 500});\n");
      out.write("  \t\t\t}    \n");
      out.write("  \t\t});\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$('#exit').click(function() {\n");
      out.write("        $(\"#login-parameter\").show();\n");
      out.write("      \t$(\"#query-buttons\").hide();\n");
      out.write("        $(\"#query-box\").html(\"\");\n");
      out.write("      \t$(\"#result\").html(\"\");\n");
      out.write("\t\tif($('#dialog').dialog(\"instance\")){\n");
      out.write("\t        $(\"#dialog\").html(\"\");\n");
      out.write("\t\t\t$('#dialog').dialog(\"destroy\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("function setParameter() {\n");
      out.write("\tvar value = $('#preset').val();\n");
      out.write("\t$(\"#driver\").val(presets[value][1]);\n");
      out.write("\t$(\"#url\").val(presets[value][2]);\n");
      out.write("\t$(\"#user\").val(presets[value][3]);\n");
      out.write("\t$(\"#password\").val(presets[value][4]);\n");
      out.write("};\n");
      out.write("\n");
      out.write("function changeTheme() {\n");
      out.write("\t$('#theme').attr(\"href\",\"");
      out.print( application.getContextPath() );
      out.write("/css/\" + $(\"#css-list\").val());\n");
      out.write("};\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<title>db-view</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"css-selector\">\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<td>theme</td>\n");
      out.write("<td>\n");
      out.write("<select id=\"css-list\" onchange=\"changeTheme()\">\n");
      out.write("</select>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<hr/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"header\">\n");
      out.write("<table cellpadding=\"\" class=\"header\">\n");
      out.write("<tr>\n");
      out.write("<td align=\"left\"><h1>db-view 3.0</h1></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td align=\"right\">buid on 9th June 2015.<br>developed by dmc system service.</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<hr/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"login-parameter\">\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<td>database</td>\n");
      out.write("<td>\n");
      out.write("<select id=\"preset\" onchange=\"setParameter()\">\n");
      out.write("</select>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<td>driver</td>\n");
      out.write("<td><input id=\"driver\" name=\"driver\" type=\"text\" size=\"40pix\" value=\"");
      out.print( bean.getDriver() );
      out.write("\"/></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>url</td>\n");
      out.write("<td><input id=\"url\" name=\"url\" type=\"text\" size=\"40pix\" value=\"");
      out.print( bean.getUrl() );
      out.write("\"/></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>user</td>\n");
      out.write("<td><input id=\"user\" name=\"user\" type=\"text\" size=\"40pix\" value=\"");
      out.print( bean.getUser() );
      out.write("\"/></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>password</td>\n");
      out.write("<td><input id=\"password\" name=\"password\" type=\"text\" size=\"40pix\" value=\"");
      out.print( bean.getPassword() );
      out.write("\"/></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<input class=\"button\" type=\"button\" value=\"login\" id=\"login\"/>\n");
      out.write("<hr/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"query-box\">\n");
      out.write("</div>\n");
      out.write("<div id=\"query-buttons\">\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<td><input type=\"button\" value=\"execute\" id=\"execute\"/></td>\n");
      out.write("<td><input type=\"button\" value=\"history\" id=\"history\"/></td>\n");
      out.write("<td><input type=\"button\" value=\"exit\" id=\"exit\"/></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<hr/>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"result\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"dialog\" title=\"history\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
